// Do not edit this file directly
// Edit score-factors.json instead
// Use npm run generate-score-factors to update it
const SCORE = {
  PR_FACTOR: 2,
  REVIEWED_MR_FACTOR: 2,
  ISSUES_FACTOR: 0.5,
  COMMIT_FACTOR: 10,
};

export default SCORE;
