package handler

// Score factors (generated from score-factors.json)
// Do not edit this file directly
// Use npm run generate-score-factors to update it
const (
	CommitFactor     = 10
	IssueFactor      = 0.5
	PRFactor         = 2
	ReviewedMRFactor = 2
)

func CalculateScore(commits, issues, prs, reviewed int64) float64 {
	return float64(commits)*CommitFactor + float64(issues)*IssueFactor + float64(prs)*PRFactor + float64(reviewed)*ReviewedMRFactor
}
