package models

import "time"

// Report model stored in the database.
// Data field contains the JSON report generated by the AI.
//
// PromptVersion identifies which prompt + schema produced this row.
// Legacy rows (pre-prompt-v2) have value 1 — backfilled at startup.
// Prompt v2 adds summary_short / summary_long / team fields per project.
type Report struct {
	ID            string    `gorm:"primaryKey" json:"id"`
	CreatedAt     time.Time `json:"createdAt"`
	Data          string    `json:"data" gorm:"type:json"`
	UserPrompt    string    `json:"userPrompt" gorm:"type:text"`
	PromptVersion int       `json:"promptVersion" gorm:"default:1;not null"`
}
