package models

import "time"

// Report model stored in the database.
// Data field contains the JSON report generated by the AI.
type Report struct {
	ID         string    `gorm:"primaryKey" json:"id"`
	CreatedAt  time.Time `json:"createdAt"`
	Data       string    `json:"data" gorm:"type:json"`
	UserPrompt string    `json:"userPrompt" gorm:"type:text"` // Field to store the input prompt
}
